"""add graph_status to sites

Revision ID: 8cec9ce972b2
Revises: 1d9a89af354e
Create Date: 2026-04-18 22:24:39.736473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cec9ce972b2'
down_revision: Union[str, Sequence[str], None] = '1d9a89af354e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('graph_status', sa.String(length=50), nullable=False, server_default='idle'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'graph_status')
    # ### end Alembic commands ###
