"""Add auth_id to Tenant

Revision ID: aa7e2406075a
Revises: 8587400decfe
Create Date: 2026-04-05 21:40:21.956439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7e2406075a'
down_revision: Union[str, Sequence[str], None] = '8587400decfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('auth_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_auth_id'), 'tenants', ['auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_auth_id'), table_name='tenants')
    op.drop_column('tenants', 'auth_id')
    # ### end Alembic commands ###
