"""remove_cascade_deletes

Revision ID: aced338245e1
Revises: d7d5737912dc
Create Date: 2026-04-11 18:15:40.980190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aced338245e1'
down_revision: Union[str, Sequence[str], None] = 'd7d5737912dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('data_sources_site_id_fkey'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(None, 'data_sources', 'sites', ['site_id'], ['id'])
    op.drop_constraint(op.f('documents_data_source_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'data_sources', ['data_source_id'], ['id'])
    op.drop_constraint(op.f('sites_tenant_id_fkey'), 'sites', type_='foreignkey')
    op.create_foreign_key(None, 'sites', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.create_foreign_key(op.f('sites_tenant_id_fkey'), 'sites', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_data_source_id_fkey'), 'documents', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.create_foreign_key(op.f('data_sources_site_id_fkey'), 'data_sources', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
