"""update_embedding_dim_to_3072

Revision ID: d7d5737912dc
Revises: 2453969c3c68
Create Date: 2026-04-08 21:47:28.083723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d5737912dc'
down_revision: Union[str, Sequence[str], None] = '2453969c3c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(3072)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(768)")
    # ### end Alembic commands ###
